### ISSUE TITLE
empty log.log() makes it crash

### ISSUE THREAD

**Issue by spaetz** [mh-/exposure-notification-ble-python#1]
**DOH. Update: The issue is: log.log() in line 52 of lib/en_tx_service.py :-)
Right now, it must not be empty.**

Pull request #3  fixes this

**Comment by spaetz** [comment]
A nicer way to fix this, would be to use a proper logging.getLogger and to add a Filter which suppresses and duplicate lines. This way we would have access to the full logging machinery with outputs, error levels etc...
But that would probably be overkill now (I imagine this could be done in like 40 lines of code...)

**Comment by mh-** [comment]
Thanks :)
